/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author mac
 */
public class bookpro extends javax.swing.JFrame {

    /**
     * Creates new form bookpro
     */
    public bookpro() {
        initComponents();
        setLayout(null);
        setSize(997, 745);
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
        jMenu6.setText("                               Account:   "+loginpro.t1.getText());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        le = new javax.swing.JLabel();
        la = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        ld = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        ll1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/small logo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 0, 210, 130);

        le.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        le.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 12, 12)));
        getContentPane().add(le);
        le.setBounds(50, 620, 250, 50);

        la.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        la.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 12, 12)));
        getContentPane().add(la);
        la.setBounds(50, 250, 250, 50);

        lb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 12, 12)));
        getContentPane().add(lb);
        lb.setBounds(50, 340, 250, 50);

        lc.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 12, 12)));
        getContentPane().add(lc);
        lc.setBounds(50, 430, 250, 50);

        ld.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 12, 12)));
        getContentPane().add(ld);
        ld.setBounds(50, 530, 250, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-40, 690, 1000, 12);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(-10, 220, 1000, 12);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-10, 400, 1000, 12);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(-20, 500, 1000, 12);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 310, 1000, 12);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(-40, 590, 1000, 12);

        ll1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        getContentPane().add(ll1);
        ll1.setBounds(360, 130, 300, 80);

        jButton1.setText("3:20 PM");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 240, 94, 60);

        jButton2.setText("8:40 PM");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 330, 90, 60);

        jButton4.setText("10:00 AM");
        jButton4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(360, 240, 90, 60);

        jButton5.setText("11:25 PM");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(860, 430, 90, 60);

        jButton6.setText("3:20 PM");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(490, 330, 94, 60);

        jButton7.setText("10:00 AM");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(360, 330, 90, 60);

        jButton9.setText("12:45 PM");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(490, 430, 100, 60);

        jButton10.setText("2:55 PM");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(620, 430, 90, 60);

        jButton11.setText("6:05 PM");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(740, 430, 90, 60);

        jButton12.setText("9:20 AM");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(360, 430, 90, 60);

        jButton13.setText("8:10 PM");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(490, 620, 100, 60);

        jButton14.setText("12:20 PM");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(360, 520, 90, 60);

        jButton15.setText("2:55 PM");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(360, 620, 90, 60);

        jButton8.setText("8:40 PM");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(620, 240, 90, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 0, 400, 400);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 320, 400, 400);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 0, 400, 400);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 400);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 330, 400, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 320, 400, 400);

        jMenuBar1.setForeground(new java.awt.Color(9, 0, 0));

        jMenu1.setText("                   Home                   ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("                           Movies           ");

        jCheckBoxMenuItem1.setText("Now Showing");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("                                 Search            ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Search");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("                            Account                                      ");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Dev");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        dev.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);

        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);

        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        NowShowing.setVisible(true);

    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handlin
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        dev.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);

        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        logout.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        String x,a;
        x=ll1.getText();
        a=la.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("10:00 AM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4AncestorAdded

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
                
               settings.setVisible(false);
               homepage.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               
               profile.setVisible(false);
               dev.setVisible(false);
               this.setVisible(false);
               
               search.setVisible(true);        // TODO add your
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=la.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("3:20 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=la.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("8:20 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=lb.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("10:00 AM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=lb.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("3:20 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=lb.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("8:40 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=lc.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("9:20 AM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=lc.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("12:45 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=lc.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("2:55 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=lc.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("6:05 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=lc.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("11:25 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=ld.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("12:20 pM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
         String x,a;
        x=ll1.getText();
        a=le.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("2:55 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        String x,a;
        x=ll1.getText();
        a=le.getText();
        
        book1pro book1 = new book1pro();
        book1pro.lb1.setText(x);
        book1pro.lbb2.setText(a);
        book1pro.lb3.setText("8:10 PM");
        book1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookpro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookpro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookpro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookpro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookpro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public static javax.swing.JLabel la;
    public static javax.swing.JLabel lb;
    public static javax.swing.JLabel lc;
    public static javax.swing.JLabel ld;
    public static javax.swing.JLabel le;
    public static javax.swing.JLabel ll1;
    // End of variables declaration//GEN-END:variables
}
