/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author mac
 */
public class book1pro extends javax.swing.JFrame {

    /**
     * Creates new form book1pro
     */
    public book1pro() {
        initComponents();
        
        
        initComponents();
        setLayout(null);
        setSize(997, 745);
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jMenu6.setText("                               Account:   "+loginpro.t1.getText());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ba1 = new javax.swing.JButton();
        ba2 = new javax.swing.JButton();
        ba3 = new javax.swing.JButton();
        ba4 = new javax.swing.JButton();
        ba5 = new javax.swing.JButton();
        ba6 = new javax.swing.JButton();
        ba7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ba9 = new javax.swing.JButton();
        ba8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ba10 = new javax.swing.JButton();
        ba11 = new javax.swing.JButton();
        ba12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ba13 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ba14 = new javax.swing.JButton();
        ba15 = new javax.swing.JButton();
        ba16 = new javax.swing.JButton();
        ba17 = new javax.swing.JButton();
        ba18 = new javax.swing.JButton();
        ba19 = new javax.swing.JButton();
        ba20 = new javax.swing.JButton();
        ba21 = new javax.swing.JButton();
        ba22 = new javax.swing.JButton();
        ba23 = new javax.swing.JButton();
        ba24 = new javax.swing.JButton();
        ba25 = new javax.swing.JButton();
        ba26 = new javax.swing.JButton();
        ba27 = new javax.swing.JButton();
        ba28 = new javax.swing.JButton();
        ba29 = new javax.swing.JButton();
        ba30 = new javax.swing.JButton();
        ba31 = new javax.swing.JButton();
        ba32 = new javax.swing.JButton();
        ba33 = new javax.swing.JButton();
        ba34 = new javax.swing.JButton();
        ba35 = new javax.swing.JButton();
        ba36 = new javax.swing.JButton();
        ba37 = new javax.swing.JButton();
        ba38 = new javax.swing.JButton();
        ba39 = new javax.swing.JButton();
        ba40 = new javax.swing.JButton();
        ba41 = new javax.swing.JButton();
        ba42 = new javax.swing.JButton();
        ba43 = new javax.swing.JButton();
        ba44 = new javax.swing.JButton();
        ba45 = new javax.swing.JButton();
        ba46 = new javax.swing.JButton();
        ba47 = new javax.swing.JButton();
        ba48 = new javax.swing.JButton();
        ba49 = new javax.swing.JButton();
        ba50 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        ba51 = new javax.swing.JButton();
        ba52 = new javax.swing.JButton();
        ba53 = new javax.swing.JButton();
        ba54 = new javax.swing.JButton();
        ba55 = new javax.swing.JButton();
        ba56 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        la3 = new javax.swing.JLabel();
        la1 = new javax.swing.JLabel();
        la2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lbb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(null);

        jMenuBar2.setForeground(new java.awt.Color(9, 0, 0));

        jMenu3.setText("                   Home                   ");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Home");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("                           Movies           ");

        jCheckBoxMenuItem2.setText("Now Showing");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem2);

        jMenuItem8.setText("Coming Soon");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("                                 Search            ");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        jMenu8.setText("                            Account                                      ");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Profile");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Settings");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuItem11.setText("Dev");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Logout");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuBar2.add(jMenu8);

        jFrame1.setJMenuBar(jMenuBar2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/small logo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 6, 193, 116);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/Screen Shot 2017-12-19 at 2.42.23 PM.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(391, 571, 443, 30);

        jLabel3.setText("B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 381, 7, 16);

        jLabel4.setText("A");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 459, 9, 16);

        ba1.setText("1");
        ba1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ba1MouseClicked(evt);
            }
        });
        ba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba1ActionPerformed(evt);
            }
        });
        getContentPane().add(ba1);
        ba1.setBounds(265, 446, 63, 44);

        ba2.setText("2");
        ba2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ba2MouseClicked(evt);
            }
        });
        getContentPane().add(ba2);
        ba2.setBounds(346, 446, 63, 44);

        ba3.setText("3");
        ba3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ba3MouseClicked(evt);
            }
        });
        getContentPane().add(ba3);
        ba3.setBounds(427, 446, 63, 44);

        ba4.setText("4");
        getContentPane().add(ba4);
        ba4.setBounds(508, 446, 63, 44);

        ba5.setText("5");
        getContentPane().add(ba5);
        ba5.setBounds(589, 446, 64, 44);

        ba6.setText("6");
        getContentPane().add(ba6);
        ba6.setBounds(671, 446, 64, 44);

        ba7.setText("7");
        getContentPane().add(ba7);
        ba7.setBounds(753, 368, 64, 44);

        jButton8.setText("8");
        getContentPane().add(jButton8);
        jButton8.setBounds(835, 446, 64, 44);

        ba9.setText("9");
        getContentPane().add(ba9);
        ba9.setBounds(917, 446, 64, 44);

        ba8.setText("1");
        getContentPane().add(ba8);
        ba8.setBounds(265, 368, 63, 44);

        jLabel5.setText("C");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 306, 9, 16);

        jLabel6.setText("D");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 234, 10, 16);

        jLabel7.setText("E");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(207, 152, 10, 16);

        ba10.setText("1");
        getContentPane().add(ba10);
        ba10.setBounds(265, 293, 63, 44);

        ba11.setText("1");
        getContentPane().add(ba11);
        ba11.setBounds(265, 221, 63, 44);

        ba12.setText("1");
        getContentPane().add(ba12);
        ba12.setBounds(263, 140, 60, 44);

        jLabel8.setText("F");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(211, 83, 9, 16);

        ba13.setText("1");
        getContentPane().add(ba13);
        ba13.setBounds(265, 70, 63, 44);

        jLabel9.setText("G");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(211, 19, 9, 16);

        ba14.setText("1");
        getContentPane().add(ba14);
        ba14.setBounds(265, 6, 63, 44);

        ba15.setText("2");
        getContentPane().add(ba15);
        ba15.setBounds(346, 368, 63, 44);

        ba16.setText("2");
        getContentPane().add(ba16);
        ba16.setBounds(346, 293, 63, 44);

        ba17.setText("2");
        getContentPane().add(ba17);
        ba17.setBounds(346, 221, 63, 44);

        ba18.setText("2");
        getContentPane().add(ba18);
        ba18.setBounds(350, 140, 63, 44);

        ba19.setText("2");
        getContentPane().add(ba19);
        ba19.setBounds(346, 70, 63, 44);

        ba20.setText("2");
        getContentPane().add(ba20);
        ba20.setBounds(346, 6, 63, 44);

        ba21.setText("3");
        getContentPane().add(ba21);
        ba21.setBounds(427, 368, 63, 44);

        ba22.setText("3");
        getContentPane().add(ba22);
        ba22.setBounds(427, 293, 63, 44);

        ba23.setText("3");
        getContentPane().add(ba23);
        ba23.setBounds(427, 221, 63, 44);

        ba24.setText("3");
        getContentPane().add(ba24);
        ba24.setBounds(430, 140, 63, 44);

        ba25.setText("3");
        getContentPane().add(ba25);
        ba25.setBounds(427, 70, 63, 44);

        ba26.setText("3");
        getContentPane().add(ba26);
        ba26.setBounds(427, 6, 63, 44);

        ba27.setText("4");
        getContentPane().add(ba27);
        ba27.setBounds(508, 368, 63, 44);

        ba28.setText("4");
        getContentPane().add(ba28);
        ba28.setBounds(508, 293, 63, 44);

        ba29.setText("4");
        getContentPane().add(ba29);
        ba29.setBounds(508, 221, 63, 44);

        ba30.setText("4");
        getContentPane().add(ba30);
        ba30.setBounds(510, 140, 63, 44);

        ba31.setText("4");
        getContentPane().add(ba31);
        ba31.setBounds(508, 70, 63, 44);

        ba32.setText("4");
        getContentPane().add(ba32);
        ba32.setBounds(508, 6, 63, 44);

        ba33.setText("5");
        getContentPane().add(ba33);
        ba33.setBounds(589, 368, 64, 44);

        ba34.setText("5");
        getContentPane().add(ba34);
        ba34.setBounds(589, 293, 64, 44);

        ba35.setText("5");
        getContentPane().add(ba35);
        ba35.setBounds(589, 221, 64, 44);

        ba36.setText("5");
        getContentPane().add(ba36);
        ba36.setBounds(590, 140, 64, 44);

        ba37.setText("5");
        getContentPane().add(ba37);
        ba37.setBounds(589, 70, 64, 44);

        ba38.setText("5");
        getContentPane().add(ba38);
        ba38.setBounds(589, 6, 64, 44);

        ba39.setText("6");
        getContentPane().add(ba39);
        ba39.setBounds(671, 368, 64, 44);

        ba40.setText("6");
        getContentPane().add(ba40);
        ba40.setBounds(671, 293, 64, 44);

        ba41.setText("6");
        getContentPane().add(ba41);
        ba41.setBounds(671, 221, 64, 44);

        ba42.setText("6");
        getContentPane().add(ba42);
        ba42.setBounds(670, 140, 64, 44);

        ba43.setText("6");
        getContentPane().add(ba43);
        ba43.setBounds(671, 70, 64, 44);

        ba44.setText("6");
        getContentPane().add(ba44);
        ba44.setBounds(671, 6, 64, 44);

        ba45.setText("7");
        getContentPane().add(ba45);
        ba45.setBounds(753, 446, 64, 44);

        ba46.setText("7");
        getContentPane().add(ba46);
        ba46.setBounds(753, 293, 64, 44);

        ba47.setText("7");
        getContentPane().add(ba47);
        ba47.setBounds(753, 221, 64, 44);

        ba48.setText("7");
        getContentPane().add(ba48);
        ba48.setBounds(750, 140, 64, 44);

        ba49.setText("7");
        getContentPane().add(ba49);
        ba49.setBounds(753, 70, 64, 44);

        ba50.setText("7");
        getContentPane().add(ba50);
        ba50.setBounds(753, 6, 64, 44);

        jButton9.setText("8");
        getContentPane().add(jButton9);
        jButton9.setBounds(835, 293, 64, 44);

        jButton10.setText("8");
        getContentPane().add(jButton10);
        jButton10.setBounds(835, 368, 64, 44);

        jButton11.setText("8");
        getContentPane().add(jButton11);
        jButton11.setBounds(835, 221, 64, 44);

        jButton12.setText("8");
        getContentPane().add(jButton12);
        jButton12.setBounds(840, 140, 64, 44);

        jButton13.setText("8");
        getContentPane().add(jButton13);
        jButton13.setBounds(835, 70, 64, 44);

        jButton14.setText("8");
        getContentPane().add(jButton14);
        jButton14.setBounds(835, 6, 64, 44);

        ba51.setText("9");
        getContentPane().add(ba51);
        ba51.setBounds(917, 368, 64, 44);

        ba52.setText("9");
        getContentPane().add(ba52);
        ba52.setBounds(917, 293, 64, 44);

        ba53.setText("9");
        getContentPane().add(ba53);
        ba53.setBounds(917, 221, 64, 44);

        ba54.setText("9");
        getContentPane().add(ba54);
        ba54.setBounds(920, 140, 64, 44);

        ba55.setText("9");
        getContentPane().add(ba55);
        ba55.setBounds(917, 70, 64, 44);

        ba56.setText("9");
        getContentPane().add(ba56);
        ba56.setBounds(917, 6, 64, 44);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Rs 300 PER TICKET");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(44, 134, 140, 17);
        getContentPane().add(t1);
        t1.setBounds(70, 410, 103, 26);

        jLabel11.setText("Ticket(s):");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 410, 58, 16);

        la3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        la3.setText("Time:");
        getContentPane().add(la3);
        la3.setBounds(80, 300, 40, 16);

        la1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        la1.setText("Movie Name:");
        getContentPane().add(la1);
        la1.setBounds(60, 170, 90, 17);

        la2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        la2.setText("Cinema:");
        getContentPane().add(la2);
        la2.setBounds(70, 230, 60, 16);
        getContentPane().add(lb1);
        lb1.setBounds(30, 190, 150, 20);
        getContentPane().add(lbb2);
        lbb2.setBounds(30, 260, 150, 20);
        getContentPane().add(lb3);
        lb3.setBounds(30, 330, 150, 20);

        jMenuBar1.setForeground(new java.awt.Color(9, 0, 0));

        jMenu1.setText("                   Home                   ");

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("                           Movies           ");

        jCheckBoxMenuItem1.setText("Now Showing");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("                                 Search            ");

        jMenuItem13.setText("Search");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("                            Account                                      ");

        jMenuItem5.setText("Dev");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        dev.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);

        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);

        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        NowShowing.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);

        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);
        comingsoon.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handlin
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);

        dev.setVisible(false);
        this.setVisible(false);

        profile.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        settings.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        dev.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);

        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        logout.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void ba1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ba1MouseClicked
        // TODO add your handling code here:
        int tc=0;
        
        tc=tc+1;
        t1.setText(Integer.toString(tc));
        
        
        
            
    }//GEN-LAST:event_ba1MouseClicked

    private void ba2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ba2MouseClicked
        // TODO add your handling code here:
        int tc=0;
        
        tc=tc+1;
        t1.setText(Integer.toString(tc));
        
        
        
    }//GEN-LAST:event_ba2MouseClicked

    private void ba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba1ActionPerformed
        // TODO add your handling code here:
         int tc=0;
        
        tc=tc+1;
        t1.setText(Integer.toString(tc));
    }//GEN-LAST:event_ba1ActionPerformed

    private void ba3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ba3MouseClicked
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_ba3MouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
                
               settings.setVisible(false);
               homepage.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               
               profile.setVisible(false);
               dev.setVisible(false);
               this.setVisible(false);
               
               search.setVisible(true);        // TODO add your
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
               settings.setVisible(false);
               dev.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               search.setVisible(false);
               profile.setVisible(false);
               this.setVisible(false);
               
               homepage.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
               
                
                
                settings.setVisible(false);
               homepage.setVisible(false);
            
               logout.setVisible(false);
               comingsoon.setVisible(false);
               search.setVisible(false);
               profile.setVisible(false);
               dev.setVisible(false);
               this.setVisible(false);
               
                NowShowing.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
                
               settings.setVisible(false);
               homepage.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               search.setVisible(false);
               profile.setVisible(false);
               this.setVisible(false);
               
               dev.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
                
                settings.setVisible(false);
               homepage.setVisible(false);
               NowShowing.setVisible(false);
               
               comingsoon.setVisible(false);
               search.setVisible(false);
               profile.setVisible(false);
               dev.setVisible(false);
               this.setVisible(false);
               
               logout.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book1pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book1pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book1pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book1pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book1pro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ba1;
    private javax.swing.JButton ba10;
    private javax.swing.JButton ba11;
    private javax.swing.JButton ba12;
    private javax.swing.JButton ba13;
    private javax.swing.JButton ba14;
    private javax.swing.JButton ba15;
    private javax.swing.JButton ba16;
    private javax.swing.JButton ba17;
    private javax.swing.JButton ba18;
    private javax.swing.JButton ba19;
    private javax.swing.JButton ba2;
    private javax.swing.JButton ba20;
    private javax.swing.JButton ba21;
    private javax.swing.JButton ba22;
    private javax.swing.JButton ba23;
    private javax.swing.JButton ba24;
    private javax.swing.JButton ba25;
    private javax.swing.JButton ba26;
    private javax.swing.JButton ba27;
    private javax.swing.JButton ba28;
    private javax.swing.JButton ba29;
    private javax.swing.JButton ba3;
    private javax.swing.JButton ba30;
    private javax.swing.JButton ba31;
    private javax.swing.JButton ba32;
    private javax.swing.JButton ba33;
    private javax.swing.JButton ba34;
    private javax.swing.JButton ba35;
    private javax.swing.JButton ba36;
    private javax.swing.JButton ba37;
    private javax.swing.JButton ba38;
    private javax.swing.JButton ba39;
    private javax.swing.JButton ba4;
    private javax.swing.JButton ba40;
    private javax.swing.JButton ba41;
    private javax.swing.JButton ba42;
    private javax.swing.JButton ba43;
    private javax.swing.JButton ba44;
    private javax.swing.JButton ba45;
    private javax.swing.JButton ba46;
    private javax.swing.JButton ba47;
    private javax.swing.JButton ba48;
    private javax.swing.JButton ba49;
    private javax.swing.JButton ba5;
    private javax.swing.JButton ba50;
    private javax.swing.JButton ba51;
    private javax.swing.JButton ba52;
    private javax.swing.JButton ba53;
    private javax.swing.JButton ba54;
    private javax.swing.JButton ba55;
    private javax.swing.JButton ba56;
    private javax.swing.JButton ba6;
    private javax.swing.JButton ba7;
    private javax.swing.JButton ba8;
    private javax.swing.JButton ba9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JLabel la1;
    public static javax.swing.JLabel la2;
    public static javax.swing.JLabel la3;
    public static javax.swing.JLabel lb1;
    public static javax.swing.JLabel lb3;
    public static javax.swing.JLabel lbb2;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
