/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author mac
 */
public class ex extends javax.swing.JFrame {

    /**
     * Creates new form ex
     */
    public ex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/small logo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 30, 210, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(700, 0, 400, 400);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 400, 400, 400);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 0, 400, 400);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 400);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 400, 400, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 400, 400, 400);

        jMenuBar1.setForeground(new java.awt.Color(9, 0, 0));

        jMenu1.setText("                   Home                   ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("                           Movies           ");

        jCheckBoxMenuItem1.setText("Now Showing");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem1.setText("Coming Soon");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("                                 Search            ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("                            Account                                      ");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Profile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setText("Settings");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Dev");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        dev.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);

        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        homepage.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);

        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        NowShowing.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);

        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);
        comingsoon.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handlin
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        search.setVisible(true);
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);

        dev.setVisible(false);
        this.setVisible(false);

        profile.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        settings.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        this.setVisible(false);

        dev.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);

        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
        this.setVisible(false);

        logout.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
