/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.*;

/**
 *
 * @author mac
 */
public class NowShowingPro extends javax.swing.JFrame {

    /**
     * Creates new form NowShowingPro
     */
    public NowShowingPro() {
        initComponents();
        
        
        
        
        setSize(1060, 780);
        
        
       setLayout(null);
       
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        jMenu8.setText("                               Account:   "+loginpro.t1.getText());

        
       
    }// </editor-fold>                  
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (4).jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 158, 181, 224);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (2).jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(55, 158, 181, 224);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (3).jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(323, 158, 181, 224);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (5).jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 158, 181, 224);

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (7).jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(323, 442, 181, 224);

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (8).jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 442, 181, 224);

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (6).jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(55, 442, 181, 224);

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage (9).jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(840, 442, 181, 224);

        jButton14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton14.setText("Book");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(920, 390, 100, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 19, 49)));
        jPanel1.setLayout(null);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gurgaon", "Delhi", "Noida" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(55, 20, 109, 23);

        t2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(223, 20, 20));
        jPanel1.add(t2);
        t2.setBounds(400, 10, 178, 35);
        t2.setVisible(false);

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);
        t1.setVisible(false);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(7, 70, 1046, 73);

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage1.png")); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(16, 8, 33, 56);

        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(800, 0, 400, 160);

        jLabel25.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(0, 0, 400, 160);

        jLabel26.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(400, 0, 400, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(850, 390, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(850, 670, 50, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 390, 50, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(590, 390, 50, 30);

        jButton18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton18.setText("Book");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(920, 670, 100, 30);

        jButton19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton19.setText("Book");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(400, 390, 100, 30);

        jButton20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton20.setText("Book");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(660, 390, 100, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 390, 50, 30);

        jButton21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton21.setText("Book");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(130, 390, 100, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 670, 50, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 670, 50, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bookf/Webp.net-resizeimage.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(590, 670, 50, 30);

        jButton22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton22.setText("Book");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(130, 670, 100, 30);

        jButton23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton23.setText("Book");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(400, 670, 100, 30);

        jButton24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton24.setText("Book");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(660, 670, 100, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(660, 150, 400, 400);

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(660, 320, 400, 400);

        jLabel21.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(400, 150, 400, 400);

        jLabel22.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 150, 400, 400);

        jLabel23.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 320, 400, 400);

        jLabel24.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/MySql/IP/pro/bg.png")); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(350, 320, 400, 400);

        jMenu3.setText("                             Home     ");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("                                         Movies           ");

        jCheckBoxMenuItem2.setText("Now Showing");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem2);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("                                      Search            ");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Search");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("                            Account                                      ");

        jMenuItem9.setText("Dev");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Logout");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
        homepage.setVisible(true);

        settings.setVisible(false);

        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
this.setVisible(false);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
        NowShowing.setVisible(true);

        settings.setVisible(false);
        homepage.setVisible(false);

        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
this.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handlin
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
        search.setVisible(true);

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);

        profile.setVisible(false);
        dev.setVisible(false);
this.setVisible(false);
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
        dev.setVisible(true);

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);
        logout.setVisible(false);
        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
        logout.setVisible(true);

        settings.setVisible(false);
        homepage.setVisible(false);
        NowShowing.setVisible(false);

        comingsoon.setVisible(false);
        search.setVisible(false);
        profile.setVisible(false);
        dev.setVisible(false);
this.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("John Wick 2");

        t1.setText("After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life.");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("Baby Driver");
        t1.setText("After being coerced into working for a crime boss, a young getaway driver finds himself taking part in\n"
                + " a heist doomed to fail.");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("2.0");
        t1.setText("2.0 is an upcoming Indian science fiction film written and directed by S. Shankar, co-written by B. Jeyamohan, and produced by Subaskaran Allirajah\n,"
                + " founder of Lyca Productions." +" This is first Indian film that is directly Shot in 3D. The movie serves as a sequel to the 2010 Tamil film\n"
                + " Enthiran,"+ " and features Rajinikanth reprising the roles of\n" +" Dr. Vaseegaran and Chitti, alongside Akshay Kumar and Amy Jackson.");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("Ittefaq");
        t1.setText("A detective seeks out the truth between two different stories of a crime scene.");
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("Tiger Zinda Hai");  
        t1.setText("Tiger Zinda Hai (English: Tiger is Alive) is an upcoming Indian action film directed by Ali Abbas Zafar. The film stars Salman Khan, Katrina Kaif,\n" +
" and Sajjad Delfrooz. And Angad Bedi, Kumud Mishra and Nawab Shah in supporting roles. It is the second in the franchise after 2012 Ek Tha Tiger\n" +
" and the second installment of Tiger film series. The film is based on the 2014 abduction of Indian nurses by ISIL.");
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("Justice League");
        t1.setText("Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his "+"\n"
            + "newfound ally, Diana Prince, to face an even greater enemy. Together, Batman and Wonder Woman work quickly to find and"+"\n"
            + "recruit a team of meta-humans to stand against this newly awakened threat."+"\n" +
             
            "But despite the formation of this unprecedented league of heroes - Batman, Wonder Woman, Aquaman, Cyborg and The Flash - it may already"+"\n"
            + " be too late to save the planet from an assault of catastrophic proportions."+"\n");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("I");
        t1.setText("A successful model's professional and personal life takes an ugly turn when he develops a hunchback due"+"\n"
                + " to an injection. He then plots revenge against the people who ruined his life.");
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        t1.setVisible(true);
        t2.setVisible(true);
        t2.setText("Fukrey Returns");
        t1.setText("Fukrey Returns is an upcoming 2017 Indian buddy comedy film, directed by Mrighdeep Singh Lamba, produced by Farhan Akhtar and Ritesh Sidhwani."+"\n"
                + " The film is the sequel to 2013 film Fukrey. Being one of the most anticipated films of 2017, it is set to release on 8 December 2017.");
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                homepage.setVisible(true);
                
               settings.setVisible(false);
               dev.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               search.setVisible(false);
               profile.setVisible(false);
               this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
        ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("Tiger Zinda Hai");
        
        
        
        ob.setVisible(true);
        this.setVisible(false);
        
       
        
        
        
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        
        
         String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
        ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("2.0");
        ob.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        
        
         String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
     ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("Ittefaq");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
         String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
        ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("John Wick 2");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        
        
         String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
       ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("Justice League");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        
         String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
        ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("I");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
      ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("Fukrey Returns");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        String x = c1.getSelectedItem().toString();
        bookpro ob = new bookpro();
      ob.la.setText("PVR: City Centre,"+x);
        ob.lb.setText("PVR: Mega Mall,"+x);
        ob.lc.setText("PVR: MGF,"+x);
        ob.ld.setText("PVR: Star Mall,"+x);
        ob.le.setText("PVR: Ambience,"+x);
        ob.ll1.setText("Baby Driver");
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        settingspro settings = new settingspro();
        homepagepro homepage = new homepagepro();
        NowShowingPro NowShowing = new NowShowingPro();
        logoutpro logout = new logoutpro();
        comingsoonpro comingsoon = new comingsoonpro();
        searchpro search = new searchpro();
        profilepro profile = new profilepro();
        devpro dev = new devpro();
                
                
               settings.setVisible(false);
               homepage.setVisible(false);
               NowShowing.setVisible(false);
               logout.setVisible(false);
               comingsoon.setVisible(false);
               
               profile.setVisible(false);
               dev.setVisible(false);
               this.setVisible(false);
               
               search.setVisible(true);        // TODO add your
    }//GEN-LAST:event_jMenuItem2ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NowShowingPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NowShowingPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NowShowingPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NowShowingPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NowShowingPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t1;
    private javax.swing.JLabel t2;
    // End of variables declaration//GEN-END:variables
}
